apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: todo-app
    tier: backend
spec:
  selector:
    app: todo-app
    tier: backend
  ports:
  - protocol: TCP
    port: 3500
    targetPort: 3500
    nodePort: 30500
    name: backend-port
  type: NodePort