apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: todo-app
    tier: frontend
spec:
  selector:
    app: todo-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
    name: frontend-port
  type: NodePort