apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: todo-app
    tier: database
spec:
  selector:
    app: todo-app
    tier: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongo-port
  type: ClusterIP