apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: todo-app
data:
  PORT: "3500"
  USE_DB_AUTH: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: todo-app
data:
  REACT_APP_BACKEND_URL: "http://localhost:30500/api/tasks"